// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {qoutes} from '../models';

export function GetLatestQuote():Promise<qoutes.Quote>;

export function GetRandomQuote():Promise<qoutes.Quote>;

export function Greet(arg1:string):Promise<string>;
